import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

texts = [
    "I think this essay reflects my personal opinion.",
    "This article is generated by an artificial intelligence model.",
    "In my experience, studying AI is challenging.",
    "The following text is generated by a large language model."
]

labels = [0, 1, 0, 1]  # 0 = Human, 1 = AI

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

model = LogisticRegression()
model.fit(X, labels)

joblib.dump(model, "model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")
